version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - django_images:/app/images
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${NGINX_CONF_FILE}:/etc/nginx/conf.d/default.conf
      - ${CERTS_FOLDER}:/ssl
      - ${FRONTEND_DIST_FOLDER}:/app/static
    depends_on:
      - django
    env_file:
      - .env

volumes:
  db_data:
  django_images: