version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ${CERTS_FOLDER}:/ssl  # Mount the folder containing your SSL certificates
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mariadb
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - db_data:/var/lib/mysql
  nginx:
    image: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ${CERTS_FOLDER}:/ssl
      - C:/temp:/app/static
    depends_on:
      - django
volumes:
  db_data: