# Generated by Django 4.1.7 on 2023-03-27 22:39

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="produce",
            name="image",
            field=models.ImageField(default=0, upload_to="images/produce/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="produce",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=recipes.models.filename_with_uuid
            ),
        ),
    ]
